const CONFIG = import.meta.env

const ACTION_URL = CONFIG.VITE_ACTION_URL,
    FACEBOOK_ACCESS_TOKEN = CONFIG.VITE_FACEBOOK_ACCESS_TOKEN,
    FACEBOOK_PIXEL_ID = CONFIG.VITE_FACEBOOK_PIXEL_ID

export {
    ACTION_URL,
    FACEBOOK_ACCESS_TOKEN,
    FACEBOOK_PIXEL_ID
}