const CONFIG = import.meta.env

const MAILCHIMP_API_KEY = CONFIG.VITE_MAILCHIMP_API_KEY,
    MAILCHIMP_SERVER_PREFIX = CONFIG.VITE_MAILCHIMP_SERVER_PREFIX

export {
    MAILCHIMP_API_KEY,
    MAILCHIMP_SERVER_PREFIX
}